### PR TITLE
Closes #4 Avatar management

### LINKED ISSUE #4: Avatar upload & delete not working
It's not a bug, it's just missing implementation (on client *and* on API side)

### PR DESCRIPTION
**Pull request by bukajsytlos**
Closes #4 Avatar management

### CODE REVIEW

**Comment by bukajsytlos** [comment]
I guess we should add confirmation dialog before delete/update and some error messages placeholder

**Comment by Brutus5000** [comment]
API support is in production by now. Will look at this soon.

**Comment by bukajsytlos** [comment]
@Brutus5000 there are still unresolved modifications as we have discussed. I need to rework the way avatars are being assigned (similiar to bans)

**Comment by Brutus5000** [comment]
Can you give an ETA when you might finish this?

**Comment by Brutus5000** [comment]
Superseeded by  d59246d.
Thanks for the preparing work though :)

**Pull request closed without merging**
